### ISSUE TITLE
Slow file transfer rate

### ISSUE THREAD

**Issue by killerbishn67** [freelan-developers/freelan#192]
I'm have a problem with transfer rate speeds between my computer and a friend who lives in the same town as me. The max download and upload for the file we were testing maxed out at 1 MB/s and idk if this is a limitation of freelan or just an error on my part.

**Comment by richman1000000** [comment]
1. who is the server? do you have peer-peer topology or it is a star?
2. are you using samba?(windows shared files)

**Comment by killerbishn67** [comment]
1. I'm the server, I think we're doing peer to peer. We just have the basic setup which was shown off on the website.
2. Yes, we're using windows shared files. Does that have a speed limitation to it?

If windows shared files does have a speed limit to it what would you recommend using then?

**Comment by richman1000000** [comment]
I forgot. What version do you use? there was a bugged version.

**Comment by killerbishn67** [comment]
I'm using 2.0.0 from what the installer says

**Comment by killerbishn67** [comment]
Well, we used iperf3 to figure out what are throughput by use our IP's and not freelan for testing and it turns out to be around 1MB/s. But I don't understand why it's so slow. My internet speed is 100 down and 15 up but we were mainly testing when I'm downloading from his computer and that's still around 1MB/s.

**Comment by richman1000000** [comment]
fixed version from #190 
https://ci.appveyor.com/api/buildjobs/3fxkduebpi0vuioh/artifacts/freelan-setup-x64-138f8565.exe

**Comment by killerbishn67** [comment]
I'm still getting around 1MB/s speeds with the new version you linked.

**Comment by richman1000000** [comment]
can you start freelan in cmd console with debug parameters? to see if there is cipher errors?
